<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.xc.union</groupId>
        <artifactId>xc-union-sdk-rebate</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>xc-union-sdk-rebate-pdd</artifactId>
    <packaging>jar</packaging>

    <name>xc-union-sdk-pdd</name>
    <description>拼多多SDK</description>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.25</version>
        </dependency>
        <dependency>
            <groupId>com.pdd.sdk</groupId>
            <artifactId>pop-sdk</artifactId>
            <version>1.19.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/pop-sdk-1.19.4-all.jar</systemPath>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>lib</directory>
                <targetPath>BOOT-INF/lib/</targetPath>
                <includes>
                    <include>**/*.jar</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>
