server:
  port: 9999
  # 配置静态资源启用 gzip 压缩
  compression:
    enabled: true
    min-response-size: 128
# 配置主数据源
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/xc_union?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: xc_union
    password: xc_union

magic-api:
  web: /magic/web
  resource:
    location: data/magic-api
# 其它配置请参考 https://ssssssss.org/magic-api/config/
  response-code:
    success: 200 #执行成功的code值
    invalid: 400 #参数验证未通过的code值
    exception: 500 #执行出现异常的code值

# 返利联盟配置
union:
  # 淘宝客
  tbk:
    app-key:
    app-secret:
    adzone-id:
  # 拼多多
  pdd:
    client-id:
    client-secret:
  # 京东联盟
  jd:
    access-token:
    app-key:
    app-secret:
  # 大淘客
  dtk:
    app-key:
    app-secret: